language: ruby
os:
  - osx
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
  - source ~/.bashrc
script:
  - nvm install stable
  - nvm use stable

  - npm install
  - npm run lint
  - npm test

  - npm run dist
  - npm run pack:osx
  - npm run build:osx

env:
  global:
    secure: Z1vZmJKiaxkCn1Xt469w9x+zmOE219yEDSIIHQOpTeWvkGkBzVu8ab0CbFAWicV6tyNQch0AojDh36dMlpSaQVJJyN0j/bgfEoN0KWxR2IV+yFjfVDlUgqwws5qCcmGGQpNJaKelPFZKacewbS7axl9FzcE0A0C4viLTiXwefOKLhCtbk8/0gBmuLachaABC4e7+i2F3Uq5l3H46Ky+hXvmOkR/xYo9r7uo3RIrklkULPpf1SQ3MDtNJ1b2kiyPPt0Hu4SGlr3K8JWtwX0WNVQaAPJLfMyqff6ctg/568TudUs4JN4juc1rv9UaSQ9WqDqnLCAdz3dAxVC4cOUK4U2I4kkEafeE+7Gc9qsB+TdbakbHEle51lrMzN0+UbXTs7LAkDuOkX6E+EtVdPhKpYPo9UHXhkeOEdJrd1l5M7N/snyEo1gxHYnFSQBXKau1PP1Lpw7RZ3X9m88s8juc1DC1sF2Bx0vVDyfq710qJmHVrFZpqe+P1B0z6pEq9I6LVggeDsPxc2RrNKyfwh2YI4mYgs20h7y6nmAudw1ekl+A5AtsIrMTatFPP/BJoKTa/5X2Kf5HpVrZJmtLNzGr/Mwz9puaJMjtb5dQkMmR36IIrT4+L/VG7san3nVlJJLA9I78tWaOzxzJoykqS3EDXoC1EYbOQ+qDEJUwTddEv2s8=

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file: ./release/osx/ESRScan.dmg
  skip_cleanup: true
  on:
    tags: true
after_deploy: ./scripts/travis-after-deploy.sh
